spring:
  datasource:
    url: jdbc:mysql://47.100.115.59:3306/HospitalWard?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: master-lee
    password: 286916
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non-null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
logging:
  level:
    #设置mybatis的sql语句打印到控制台。
    com.example.hospitalward.mapper: trace

mybatis:
  mapper-locations: classpath*:**/*Mapper.xml
